steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '--no-cache', '-t', 'gcr.io/$PROJECT_ID/articles', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/articles']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: ['run', 'deploy', 'articles', '--image', 'gcr.io/$PROJECT_ID/articles', '--platform', 'managed', '--region', 'us-central1', '--allow-unauthenticated', '--port', '8080']
images:
  - 'gcr.io/$PROJECT_ID/articles'